In [1]:
import pandas as pd
df = pd.read_csv('https://www.insee.fr/fr/statistiques/fichier/6800675/v_commune_2023.csv')
df.head(1)

,TYPECOM,COM,REG,DEP,CTCD,ARR,TNCC,NCC,NCCENR,LIBELLE,CAN,COMPARENT
0,COM,01001,84.0,01,01D,012,5,ABERGEMENT CLEMENCIAT,Abergement-Clémenciat,L'Abergement-Clémenciat,0108,NaN

In [3]:
import geopandas as gpd
gdf = gpd.read_file(r'c:\Users\dmarin\Dropbox\Pro\OpenDC\99 Projects\0146-TD Python - ENSAE\02 Work\02 Cours\notebooks\data\contours-iris-pe.gpkg')
print(f'{len(gdf.index):,} IRIS')
gdf.head()

48,512 IRIS

,cleabs,code_insee,nom_commune,iris,code_iris,nom_iris,type_iris,geometry
0,IRIS____0000000670430101,67043,Bischheim,0101,670430101,Bischheim,A,"MULTIPOLYGON (((1052052.5 6848302.2, 1052346.7..."
1,IRIS____0000000132020101,13202,Marseille 2e Arrondissement,0101,132020101,Marseille 2e Arrondissement,A,"MULTIPOLYGON (((892392.4 6249040.5, 892189 624..."
2,IRIS____0000000561850101,56185,Quéven,0101,561850101,Quéven,A,"MULTIPOLYGON (((217035.9 6759952.7, 216941.9 6..."
3,IRIS____0000000930630101,93063,Romainville,0101,930630101,Romainville,A,"MULTIPOLYGON (((659020 6865990.2, 658978.6 686..."
4,IRIS____0000000940480101,94048,Marolles-en-Brie,0101,940480101,Marolles-en-Brie,A,"MULTIPOLYGON (((667454 6850589.8, 667714.1 685..."

In [4]:
lkp_dept = pd.read_csv(r'c:\Users\dmarin\Dropbox\Pro\OpenDC\99 Projects\0146-TD Python - ENSAE\02 Work\02 Cours\notebooks\data\lkp_dept_region.csv', sep=';', encoding='ansi')
lkp_dept.head(1)

   DEP_ID DEP NOM_DEPT  REG_ID  REG_NEW_ID            REGION_NEW
0       1  01      Ain      82          84  Auvergne-Rhône-Alpes

In [8]:
df_pop = pd.read_csv(r'c:\Users\dmarin\Dropbox\Pro\OpenDC\99 Projects\0146-TD Python - ENSAE\02 Work\02 Cours\notebooks\data\pop-IRIS-2022.csv', sep=';')
print(f'{len(df_pop):,} IRIS')
df_pop.head()

49,276 IRIS

C:\Users\dmarin\AppData\Local\Temp\ipykernel_22200\599788689.py:1: DtypeWarning: Columns (0,1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_pop = pd.read_csv(r'c:\Users\dmarin\Dropbox\Pro\OpenDC\99 Projects\0146-TD Python - ENSAE\02 Work\02 Cours\notebooks\data\pop-IRIS-2022.csv', sep=';')

,IRIS,COM,TYP_IRIS,LAB_IRIS,P22_POP,P22_POP0002,P22_POP0305,P22_POP0610,P22_POP1117,P22_POP1824,...,C22_F15P_STAT_GSEC14_24,C22_F15P_STAT_GSEC15_25,C22_F15P_STAT_GSEC16_26,C22_F15P_STAT_GSEC32,C22_F15P_STAT_GSEC40,P22_POP_FR,P22_POP_ETR,P22_POP_IMM,P22_PMEN,P22_PHORMEN
0,10010000,1001,Z,5,859.000000,33.000000,28.000000,56.000000,81.000000,30.000000,...,44.177143,83.445714,29.451429,88.354286,29.451429,849.000000,10.000000,19.000000,859.000000,0.000000
1,10020000,1002,Z,5,273.000000,6.000000,12.000000,19.000000,34.000000,11.000000,...,24.818182,14.890909,4.963636,24.818182,4.963636,272.000000,1.000000,3.000000,273.000000,0.000000
2,10040101,1004,H,1,2057.937539,98.571487,56.977868,139.534470,174.716876,352.838927,...,91.718672,276.808212,53.269481,211.569253,130.462435,1767.609911,290.327628,247.897397,1694.944143,362.993396
3,10040102,1004,H,1,3986.920098,147.358644,164.785678,239.997491,358.323293,418.123741,...,212.408021,415.766092,146.090052,356.309707,323.247325,3353.940535,632.979564,772.537275,3986.920098,0.000000
4,10040201,1004,H,1,4520.666637,194.195739,196.752408,281.247669,376.641507,378.855321,...,356.149732,508.642655,165.866837,691.215336,346.153660,4115.886111,404.780526,442.331955,4432.668238,87.998399

In [9]:
df_pop = df_pop.loc[~df_pop['DEP'].isin(['2A', '2B'])]
df_pop.loc[:, 'IRIS'] = df_pop.loc[:, 'IRIS'].astype(int)
print(f'{len(df_pop):,} IRIS hors Corse')
df_pop.head()
# df_pop[['IRIS', 'COM', 'P22_POP']].to_parquet(r'c:\Users\dmarin\Dropbox\Pro\OpenDC\99 Projects\0146-TD Python - ENSAE\02 Work\02 Cours\notebooks\data\pop-IRIS-2022.parquet')

KeyError: 'DEP'