<a href="https://colab.research.google.com/github/daniel-odc/td_pythonds_ensae/blob/main/notebooks/cookbook_geopandas_OpenDC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

clockify: 09/02: 18h45 - 20h45

# Cookbook `GeoPandas`
12/02/2026 - Daniel Marin (dmarin@open-dc.com)

**Objet de la formation:**
Prise en main de la librairie `GeoPandas` du langage `Python` pour le traitement et la visualisation de données géographiques:
> Affichage de cartes <br>
> Fusion avec des sources de données externes <br>
> Opérations géographiques (calculs de distances, intersections de zones etc.)

**Pré-requis:**
- Bases en programation `Python`
- Logiciel [QGIS](URL) installé (pour la visualisation et la mise en forme des données)
- Adresse `gmail` valide (pour le développement sous [Google Colab](URL))

## Liens et sources de données

- Nombreux visuels et exemples tirés du cours de 2ème année d'ENSAE [Python pour la data science](URL) de [Lino Galiana](URL).
- Documentation [`Pandas`](URL)
- Documentation [`GeoPandas`](URL)
- Sources de données:
    - [Contours géographiques des départements de France métropolitaine](URL)
    - [Contours géographiques des IRIS de France métropolitaine](URL)
    - [Données de population par IRIS en France en 2019](URL)
    - [Liste des stations de transport en commun de la métropole du Grand Lyon](URL)
    - [Liste des entrées de stations de métro de la métropole du Grand Lyon](URL)

Tous les fichiers sont disponibles en téléchargement local [ici](URL).

## 1er développement sur [Google Colab](URL)

*Intérêt de Google Colab*:
- Pas d'installation locale de `Python`
- Gratuit et accessible à tout le monde, sous réserve de disposer d'une adresse `Gmail`
- Développement dans le navigateur ==> pas d'installation d'IDE nécessaire
- Environnement `Jupyter Notebook` intégré
- Partage facile de scripts.

*Inconvénients*:
- Fonctionnement en ligne uniquement
- Non adapté pour de gros projets (multiples fichiers)
- Non adapté pour des traitements confidentiels (serveurs `Google`)

💡*Autres solutions*:
- [SPP Cloud](URL) pour les agents de la fonction publique française ([Étapes ici](URL slides ENSAE)).
- Installation d'un IDE ([`Pycharm`](URL) ou [`VS Code`](URL) par exemple) et d'un exécutable [`Python`](URL) pour les utilisateurs Windows (`Python` étant installé par défaut sur `Mac` et `Linux`)

## Présentation (très succinte) de [QGIS](URL)

- Système d'Information Géographique (SIG).
- Permet de réaliser des cartes, traiter des données géographiques, les mettre et forme et les communiquer.
- Logiciel libre, 100% ouvert et gratuit.

![screenshot QGIS](URL)

💡La plupart des opérations réalisables avec `GeoPandas` (buffers, calculs de distance, de surfaces etc.) le sont via l'interface de `QGIS`. L'utilisation de `GeoPandas` permet de chaîner ces opérations dans un script `Python`, ce qui rend entre autres le process plus reproductible.

💡💡Pour aller plus loin: [Tutoriel QGIS](URL)

## Rappels de base de programmation `Python`

*Note: * On ne revient pas ici sur les notions de base de programmation telles que les variables, fonctions, boucles, conditions. On se concentre sur les spécificités de `Python` par rapport aux autres langages.

### Types de base

In [ ]:
# # Les types de base: int, float, str
a = 2
b = 3.14
c = 'texte'

print(f'a={a}, b={b}, c={c}')

# # variables non allouées à un type donné:
a = 'texte'  # a passe de int à str sans problème
print(f'new a={a}')

In [ ]:
# # Listes, tuples, dictionnaires et sets:

li = [1, 2, 3]  # `list`: []
print(f'type li: {type(li)}\n{li}')

tu = (1, 2, 3)  # `tuple`: ()
print(f'type lu: {type(tu)}\n{tu}')

di = {'a': 1, 'b': 2, 'c': 3}  # `dict`: {}
print(f'type di: {type(di)}\n{di}')

st = set([1, 2, 3])  # `set`: set([...]) ou {1, 2, 3}
print(f'type st: {type(st)}\n{st}')

In [8]:
# # Listes:

li = [2, 4, 3]      # liste de 3 éléments
print(li)
print(f'1ère valeur: {li[0]}')        # l'index commence à 0

li.sort()           # tri la liste
print(li)

li.append(5)        # ajoute un élément
print(li)

li.extend([6, 7])   # ajoute une liste à la liste
print(li)

li.pop(4)           # retire le 4ème élément de la liste (et non l'élément 4 de la liste!)
print(li)

# # boucle sur les éléments:
for el in li:
    print(el)

# # boucle avec conservation des index:
for ix, el in enumerate(li):
    print(f'index {ix}, valeur: {el}')

# # Comprehension lists:
li = [i for i in range(10) if i%2 == 0]

1ère valeur: 2
[2, 3, 4]
[2, 3, 4, 5]
[2, 3, 4, 5, 6, 7]
[2, 3, 4, 5, 7]
2
3
4
5
7
index 0, valeur: 2
index 1, valeur: 3
index 2, valeur: 4
index 3, valeur: 5
index 4, valeur: 7

In [ ]:
# # Dictionnaires:
# # my_dict = {key1: val1, key2: val2}

di = {'nom': 'Crusoé', 'prénom': 'Robinson', 'âge': 42}
print(di)

di['nom'] = 'Stévenin'  # les clés sont uniques
print(di)

prenom = di.get('prénom', '???')        # clé existante
adresse = di.get('adresse', '???')      # clé manquante
print(f'prénom:\t{prenom},\nadresse:\t{adresse}')

In [ ]:
# # Tuples:

tu = (49.4545, 2.4545)  # tuple à 2 éléments
print(f'{tu[0]}, {tu[1]}')

# tu[2] = 0               # le nombre d'éléments d'un tuple est invariable (pas de méthodes `append` ou `pop`)

# tu[1] = 0               # le contenu d'un tuple n'est pas modifiable

In [7]:
# # Sets: Ensemble d'éléments uniques

st = {1, 3, 1, 2}
print(st)

st.add(4)
print(st)

st.pop()  # retire le premier élément
print(st)

st.remove(3)  # retire un élément donné
print(st)

{1, 2, 3}
{1, 2, 3, 4}
{2, 3, 4}
{2, 4}

## Mutabilité

En `Python`, seuls les types de base `int`, `float` et `str` ne sont pas mutables.

```python
a = 2
b = a
b = 3
print(f'a: {a}, b: {b}')  # le contenu de a n'a pas changé: une copie de a a été réalisée pour être alouée à b (idem si a est un float ou str)

li1 = [1, 2]
print(f'li1: {li1}')
li2 = li1
li2[0] = 0
print(f'li2: {li2}\nli1: {li1}')  # le contenu de li1 a été modifié lorsque li2 a été modifié

# # Solution: créer une copie de l'objet mutable:
li3 = li1.copy()
li3[0] = 30
print(f'li3: {li3}\nli1: {li1}')  # le contenu de li1 n'a pas été modifié lorsque li3 a été modifié
```

💡Les objets `Pandas` et `GeoPandas` qu'on verra par la suite sont mutables comme tous les objets `Python`

### Imports de modules

#### Installation d'un module

💡 Uniquement pour les modules non natifs (ex de modules natifs: `datetime`, `os`, `re` etc.)

> Dans le terminal:

```shell
pip install mon_module  # example: pip install geopandas
```

> Dans jupyter:

```python
!pip install mon_module  # notez le "!"
```

### Import de modules

💡 Toujours en tête de fichier

```python
import numpy as np  # et jamais "from numpy import *"!
import pandas as pd

df = pd.read_csv('https://www.insee.fr/fr/statistiques/fichier/6800675/v_commune_2023.csv')
# reste du code...

```

### Introduction à `Pandas`

- `Pandas`: librairie "mère" de `GeoPandas`. Librairie `Python` de base pour l’analyse de données, téléchargée 5 millions de  fois par jour.
- Permet le traitement de données tabulaires
- `GeoPandas` = `Pandas` + opérations géographiques

![Exemple données tabulaires](URL)

💡 Toutes les manipulations de cette partie fonctionnent aussi avec `GeoPandas`.


- `Serie`: objet vecteur pandas
- `Dataframe`: matrice ==> ensemble de `Series`. Les différentes colonnes peuvent être de types mixtes.
- Formats de de fichiers pour l’import de données:
  - `csv` (méthode `read_csv()`)
  - `parquet` (méthode `read_parquet()`)
  - `json` (méthode `read_json()`)
  - `txt` (méthode `read_csv()`)
  - `zip` (méthode `read_csv()`)
  - `excel` (méthode `read_excel()`)
  - `html` (méthode `read_html()`)
  - `SQL DB` (méthode `read_sql()`)
  - etc.

*Exemple:* Lecture d'un fichier `csv` disponible via une url publique:

```python
import pandas as pd

df = pd.read_csv('https://www.insee.fr/fr/statistiques/fichier/6800675/v_commune_2023.csv')
df.head()
```

#### Indexation:

```python
# # colonnes pour une condition donnée:
df.loc[df['column1']=='valeur', ['column2', 'column3']]

# # Ensemble de la colonne:
df.column1 # ne fonctionne que si les colonnes n'ont pas d'espaces ou caractères spéciaux
# # ou:
df['column1'] # renvoie une `Serie`
df[['column1']] # renvoie un `DataFrame` à une colonne

# # Accéder aux lignes:
df.iloc[0, 3]  # accès par numéro d'index: 1ère ligne, 4ème colonne. Attention à la mise à jour des index!

df.loc['nom_index', 'nom_colonne']  # accès par nom d'index
```

In [ ]:
# # Exemple simple:
import pandas as pd

df = pd.DataFrame({'year': [2012, 2014, 2013, 2014], 'month': [1, 4, 7, 10], 'sale': [55, 40, 84, 31]})

df.set_index('month', inplace=True, drop=True)

print(f'year:\n{df.year}\n')
print(f".loc:\n{df.loc[10, 'year']}\n")
print(f'.iloc:\n{df.iloc[0, 1]}\n')
df.loc[:, 'sale']

#### Statistiques descriptives

```python
df['columns'].count()
df['columns'].sum()
df['columns'].min()
df['columns'].max()
df['columns'].mean()
df['columns'].std()
df['columns'].nunique()
df['columns'].unique()
# etc.
```

#### Fusions (`merge`)

![star schema](URL)

- *Exemple avec champ commun dans les deux tables*:

```python
df_merged = df_left.merge(df_right, on=‘key’, how=‘left’) # (how=‘inner’, ‘left’, ‘right’ ou ‘outer’)
```

- *Exemple avec champs de noms différents dans les deux tables mais représentant la même donnée*:

```python
df_merged = df_left.merge(df_right, left_on=‘key_left’, right_on='key_right', how=‘left’) # (how=‘inner’, ‘left’, ‘right’ ou ‘outer’)
```

![img merge left etc.](URL)

In [ ]:
# # Exemple `merge`:
import pandas as pd

df_sale = pd.DataFrame({'year': [2012, 2014, 2013, 2014], 'month': [1, 4, 7, 10], 'sale': [55, 40, 84, 31]})

df_purchase = pd.DataFrame({'year': [2012, 2014, 2013, 2014], 'month': [1, 4, 7, 12], 'purchase': [45, 30, 90, 25]})

df_balance = df_sale.merge(df_purchase, on=['year', 'month'], how='left')  # jointure sur un ou plusieurs champs

print('Left join:')
display(df_balance)

df_balance = df_sale.merge(df_purchase, on=['year', 'month'], how='right')

print('Right join:')
display(df_balance)

df_balance = df_sale.merge(df_purchase, on=['year', 'month'], how='inner')

print('Inner join:')
display(df_balance)

df_balance = df_sale.merge(df_purchase, on=['year', 'month'], how='outer')

print('Outer join:')
display(df_balance)

#### Aggrégation (`groupby`)

```python
df_grouped = df.groupby(by=‘x’, as_index=False)[‘y’].mean()
```

- Opérations possibles:
    - `.mean()`
    - `.sum()`
    - `.min()`
    - `.max()`
    - `.std()`
    - TO COMPLETE

## `GeoPandas`

💡`DataFrame` avec une colonne `geometry` (nom de colonne fixe)

![images gdf](URL)

- Formats de fichiers:
  - `Shapefile` (.shp + .dbf + .shx + .prj)
  - `Geopackage` (.gpkg) 💡à privilégier sous `QGIS`
  - `Geoparquet` (.parquet) 💡à privilégier en développement `Python`
  - `GeoJSON` (.geojson) 💡à privilégier en développement web
  - `WKT` (.csv) 💡à privilégier pour construction "à la main"
  - etc.

### Systèmes de projection

::: columns

::: column
- Système de projection:
  - Coordonnées sphériques: GPS: longitude latitude: `WGS84` (EPSG **4326**)
  - Coordonnées projetées:
    - Cartes Google Maps: `Mercator`: EPSG **3857**
    - France métropolitaine: `Lambert 93`: EPSG **2154**
- Attribut:
  - `gdf.crs`
- Méthodes:
  - `gdf.set_crs(epsg=2154)` (à éviter habituellement!)
  - `gdf.to_crs(epsg=2154)`

:::

::: column
![](./img/geopandas_projection_system.png)
:::
:::

In [3]:
!pip install pyarrow

Defaulting to user installation because normal site-packages is not writeable
Collecting pyarrow
  Downloading pyarrow-23.0.0-cp313-cp313-win_amd64.whl.metadata (3.1 kB)
Downloading pyarrow-23.0.0-cp313-cp313-win_amd64.whl (27.6 MB)
   ---------------------------------------- 0.0/27.6 MB ? eta -:--:--
   -- ------------------------------------- 1.8/27.6 MB 12.4 MB/s eta 0:00:03
   ------ --------------------------------- 4.2/27.6 MB 11.3 MB/s eta 0:00:03
   --------- ------------------------------ 6.8/27.6 MB 11.8 MB/s eta 0:00:02
   ------------- -------------------------- 9.4/27.6 MB 12.1 MB/s eta 0:00:02
   ------------------ --------------------- 12.6/27.6 MB 12.6 MB/s eta 0:00:02
   ---------------------- ----------------- 15.2/27.6 MB 12.8 MB/s eta 0:00:01
   ------------------------- -------------- 17.8/27.6 MB 12.7 MB/s eta 0:00:01
   ----------------------------- ---------- 20.4/27.6 MB 12.7 MB/s eta 0:00:01
   --------------------------------- ------ 23.3/27.6 MB 12.9 MB/s eta 0:00:01
   -------------------------------------- - 26.2/27.6 MB 13.0 MB/s eta 0:00:01
   ---------------------------------------- 27.6/27.6 MB 12.9 MB/s eta 0:00:00
Installing collected packages: pyarrow
Successfully installed pyarrow-23.0.0

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import geopandas as gpd
gdf_iris = gpd.read_parquet(r'c:\Users\dmarin\Dropbox\Pro\OpenDC\99 Projects\0001-Misc\Geopandas_cookbook\data\IRIS_France_odc.parquet')
gdf_iris.head()

,geometry,IRIS_ID,NOM_IRIS,CODE_IRIS,COM_ID,DEP_ID,REG_NEW_ID
0,"POLYGON ((851129.6 6563369.2, 851107.5 6563355...",10010000,L'Abergement-Clémenciat,010010000,1001,1,84
1,"POLYGON ((889113.2 6549307.8, 889111.6 6549240...",10020000,L'Abergement-de-Varey,010020000,1002,1,84
2,"POLYGON ((881722.8 6544012.5, 881726.9 6543997...",10040101,Les Perouses-Triangle d'Activité,010040101,1004,1,84
3,"POLYGON ((882212.5 6542243.3, 882225.1 6542226...",10040102,Longeray-Gare,010040102,1004,1,84
4,"POLYGON ((881722.8 6544012.5, 881740 6544026.5...",10040201,Centre-Saint-Germain-Vareilles,010040201,1004,1,84

In [10]:
# # Points d'arrêt réseau TC Grand Lyon:
gdf_stops = gpd.read_file('https://data.grandlyon.com/geoserver/sytral/ows?SERVICE=WFS&VERSION=2.0.0&request=GetFeature&typename=sytral:tcl_sytral.tclarret&outputFormat=application/json&SRSNAME=EPSG:4171&sortBy=gid')
print(f"{len(gdf_stops.index):,} points d'arrêt")
print(f'Système de projection: {gdf_stops.crs}')
print(f'Dessertes uniques: {len(gdf_stops['desserte'].unique())}: {gdf_stops['desserte'].unique()}')
gdf_stops.head(2)

9,820 points d'arrêt
Système de projection: EPSG:4171
Dessertes uniques: 4559: ['C:A' 'C:R' 'A:A' ... 'BGS2:A' '37:R' 'T5:R,T5:A']

,id,nom,desserte,pmr,ascenseur,escalator,gid,last_update,last_update_fme,adresse,localise_face_a_adresse,commune,insee,zone,geometry
0,643,Croix-Rousse,C:A,1.0,1.0,1.0,12766,2026-02-09 05:03:55.400000+01:00,2026-02-09 05:03:55.400000+01:00,158 BOULEVARD DE LA CROIX ROUSSE,1.0,Lyon 4e Arrondissement,69384,1,POINT (4.83182 45.7746)
1,644,Croix-Rousse,C:R,1.0,1.0,1.0,12767,2026-02-09 05:03:55.400000+01:00,2026-02-09 05:03:55.400000+01:00,158 BOULEVARD DE LA CROIX ROUSSE,0.0,Lyon 4e Arrondissement,69384,1,POINT (4.83183 45.77446)

In [8]:
# # Lignes de métro:
gdf_lines = gpd.read_file('https://data.grandlyon.com/geoserver/sytral/ows?SERVICE=WFS&VERSION=2.0.0&request=GetFeature&typename=sytral:tcl_sytral.tcllignemf_2_0_0&outputFormat=application/json&SRSNAME=EPSG:4171&sortBy=gid')
print(f"{len(gdf_lines.index):,} lignes de métro")
print(f'Système de projection: {gdf_lines.crs}')
gdf_lines.head(2)

12 lignes de métro
Système de projection: EPSG:4171

,id,ligne,code_trace,code_ligne,type_trace,nom_trace,sens,origine,destination,nom_origine,...,code_type_ligne,nom_type_ligne,pmr,code_tri_ligne,nom_version,last_update,last_update_fme,gid,couleur,geometry
0,tcl_sytral.tcllignemf_2_0_0.A-1,A,A-1,301A,NOM,Perrache - Vaulx-en-Velin La Soie,Aller,30017,31750,Perrache.,...,REG,Régulière,True,A,Octobre2023,2023-10-10 18:55:23+02:00,2025-09-01 06:00:19.485000+02:00,27,255 0 0,"MULTILINESTRING ((4.82687 45.74961, 4.82725 45..."
1,tcl_sytral.tcllignemf_2_0_0.A-2,A,A-2,301A,NOM,Vaulx-en-Velin La Soie - Perrache,Retour,31770,30178,Vaulx-en-Velin La Soie.,...,REG,Régulière,True,A,Octobre2023,2023-10-10 18:55:23+02:00,2025-09-01 06:00:19.485000+02:00,28,255 0 0,"MULTILINESTRING ((4.9211 45.76096, 4.91751 45...."

In [12]:
# # Entrées sorties du réseau de métro:
gdf_in_out = gpd.read_file('https://data.grandlyon.com/geoserver/sytral/ows?SERVICE=WFS&VERSION=2.0.0&request=GetFeature&typename=sytral:tcl_sytral.tclstation&outputFormat=application/json&SRSNAME=EPSG:4171&sortBy=gid')
print(f"{len(gdf_in_out.index):,} entrées / sorties de métro")
print(f'Système de projection: {gdf_in_out.crs}')
gdf_in_out.head(2)

169 entrées / sorties de métro
Système de projection: EPSG:4171

,id,id_station,nom,desserte,gid,last_update,last_update_fme,geometry
0,79375486364,50851,Perrache,30101,982,2024-06-24 02:31:18+02:00,2025-09-01 06:00:11+02:00,POINT (4.82688 45.74997)
1,79376186321,50852,Perrache,30459,983,2024-06-24 02:31:18+02:00,2025-09-01 06:00:11+02:00,POINT (4.82696 45.74958)

In [15]:
gdf_metro_stations = gdf_stops.merge(gdf_in_out, left_on='id', right_on='id_station', how='inner')
gdf_metro_stations.drop_duplicates(subset='id_x', inplace=True)
print(f'{len(gdf_metro_stations.index):,} stations de métro')
gdf_metro_stations.head()

23 stations de métro

,id_x,nom_x,desserte_x,pmr,ascenseur,escalator,gid_x,last_update_x,last_update_fme_x,adresse,...,zone,geometry_x,id_y,id_station,nom_y,desserte_y,gid_y,last_update_y,last_update_fme_y,geometry_y
0,50022,Cuzin - Picasso,57:A,0.0,0.0,0.0,28878,2026-02-09 05:03:55.360000+01:00,2026-02-09 05:03:55.360000+01:00,2 RUE MAXIMILIEN DE ROBESPIERRE,...,1,POINT (4.91805 45.77584),79412687186,50022,Bellecour,"30103,46051,30201,30202",987,2024-06-24 02:31:18+02:00,2025-09-01 06:00:11+02:00,POINT (4.832 45.75726)
2,50023,Cuzin - Picasso,"57:R,PL4:R",0.0,0.0,0.0,28879,2026-02-09 05:03:55.360000+01:00,2026-02-09 05:03:55.360000+01:00,2 RUE MAXIMILIEN DE ROBESPIERRE,...,1,POINT (4.9179 45.77582),79428587292,50023,Bellecour,"30103,46051,30201,30202",988,2024-06-24 02:31:18+02:00,2025-09-01 06:00:11+02:00,POINT (4.83408 45.75817)
4,50024,Perrin - Le Rize,"C11:A,C26:R",0.0,0.0,0.0,28880,2026-02-09 05:03:55.360000+01:00,2026-02-09 05:03:55.360000+01:00,3 RUE ANTONIN PERRIN,...,1,POINT (4.88483 45.76055),79425287254,50024,Bellecour,"30103,46051,30201,30202",989,2024-06-24 02:31:18+02:00,2025-09-01 06:00:11+02:00,POINT (4.83365 45.75784)
6,50025,Perrin - Le Rize,"C11:R,C26:A",0.0,0.0,0.0,28881,2026-02-09 05:03:55.360000+01:00,2026-02-09 05:03:55.360000+01:00,18BIS RUE ANTONIN PERRIN,...,1,POINT (4.88498 45.75906),79425887240,50025,Bellecour,"46051,30103,30201,30202",990,2024-06-24 02:31:18+02:00,2025-09-01 06:00:11+02:00,POINT (4.83372 45.75771)
7,50213,La Feuillée,"C13:A,C18:A,PL2:A,TB11:R",1.0,0.0,0.0,29182,2026-02-09 05:03:55.443000+01:00,2026-02-09 05:03:55.443000+01:00,17 QUAI DE BONDY,...,1,POINT (4.82891 45.76603),79439587917,50213,Cordeliers,"46050,42744",993,2024-06-24 02:31:18+02:00,2025-09-01 06:00:11+02:00,POINT (4.83575 45.76376)